// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ2xOwfbetMXReQSeymBu9EQdhDaHudpM',
    appId: '1:691971459258:android:56018baf22fb73d86d1a83',
    messagingSenderId: '691971459258',
    projectId: 'sanogano-bf152',
    storageBucket: 'sanogano-bf152.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9bWed_zKLJXR9oOjokPJKBZEi3IgCW5M',
    appId: '1:691971459258:ios:42a08075ee6e3f906d1a83',
    messagingSenderId: '691971459258',
    projectId: 'sanogano-bf152',
    storageBucket: 'sanogano-bf152.appspot.com',
    androidClientId: '691971459258-borju63ncogdhvl5pu7jns7a2q6lhv10.apps.googleusercontent.com',
    iosClientId: '691971459258-2kcqnvbdjqiu5qq7kif18jbhuhl1r5po.apps.googleusercontent.com',
    iosBundleId: 'com.flavorstack.SanoGano',
  );
}
